name: Maven build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Store artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cloud file storage jar build
          path: target/task-tracker-scheduler-0.0.1-SNAPSHOT.jar
